######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 26 20:13:02 2011
######################################################################

QT       += core gui network
CONFIG += console

TARGET = bmailz
TEMPLATE = app


SOURCES += main.cpp\
        mainwindow.cpp \
    TCPSocket.cpp

HEADERS  += mainwindow.hh \
    TCPSocket.hh

FORMS    += mainwindow.ui

